name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "$(date)" >> activity.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add activity.txt
          git commit -m "Daily automated commit" || exit 0
          git push
